name: Build and Deploy WASM
on:
  push:
    branches:
      - master # If your default branch is named something else, change this
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build WASM package
        run: wasm-pack build --target web --out-dir pkg --no-typescript

      - name: Prepare deployment directory
        run: |
          mkdir -p ./dist
          cp index.html ./dist/
          cp 404.html ./dist/
          cp -r pkg ./dist/

          # Create README for the deployed site
          cat > ./dist/README.md << 'EOF'
          # Echoes RPG - Web Edition

          This is the web version of Echoes RPG, a cross-platform text-based RPG adventure game.

          ## Play the Game
          Open `index.html` in your browser or visit the GitHub Pages URL.

          ## About
          - Built with Rust and WebAssembly
          - Terminal-style interface in the browser
          - Full RPG gameplay with combat, inventory, and exploration

          ## Commands
          Use commands like: `look`, `go north`, `inventory`, `help`, `attack`, `use item`

          Built automatically from the main repository.
          EOF

          # Add .nojekyll to prevent Jekyll processing
          touch ./dist/.nojekyll

          echo "✅ Deployment directory prepared"
          echo "Contents of dist directory:"
          ls -la ./dist/
          echo "Contents of pkg directory:"
          ls -la ./dist/pkg/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build-artifacts
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
